src/main/java/com/mycompany/JSF/ComprasController.java
package com.mycompany.JSF;

import com.mycompany.Entity.Compras;
import com.mycompany.JSF.util.JsfUtil;
import com.mycompany.JSF.util.JsfUtil.PersistAction;
import com.mycompany.Beans.ComprasFacade;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;


@Named("comprasController")
@SessionScoped
public class ComprasController implements Serializable {


    @EJB private com.mycompany.Beans.ComprasFacade ejbFacade;
    private List<Compras> items = null;
    private Compras selected;

    public ComprasController() {
    }

    public Compras getSelected() {
        return selected;
    }

    public void setSelected(Compras selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private ComprasFacade getFacade() {
        return ejbFacade;
    }

    public Compras prepareCreate() {
        selected = new Compras();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("ComprasCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("ComprasUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("ComprasDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Compras> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Compras getCompras(java.lang.Long id) {
        return getFacade().find(id);
    }

    public List<Compras> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Compras> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass=Compras.class)
    public static class ComprasControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            ComprasController controller = (ComprasController)facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "comprasController");
            return controller.getCompras(getKey(value));
        }

        java.lang.Long getKey(String value) {
            java.lang.Long key;
            key = Long.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Long value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Compras) {
                Compras o = (Compras) object;
                return getStringKey(o.getId());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Compras.class.getName()});
                return null;
            }
        }

    }

}

src/main/webapp/compras/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ComprasCreateDlg" widgetVar="ComprasCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreateComprasTitle}">
            <h:form id="ComprasCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{comprasController.selected != null}">
                        <p:outputLabel value="#{bundle.CreateComprasLabel_productos}" for="productos" />
                        <p:selectOneMenu id="productos" value="#{comprasController.selected.productos}" required="true" requiredMessage="#{bundle.EditComprasRequiredMessage_productos}">
                            <f:selectItems value="#{productosController.itemsAvailableSelectOne}"
                                           var="productosItem"
                                           itemValue="#{productosItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.CreateComprasLabel_fecha}" for="fecha" />
                        <p:calendar id="fecha" pattern="MM/dd/yyyy" value="#{comprasController.selected.fecha}" title="#{bundle.EditComprasTitle_fecha}" required="true" requiredMessage="#{bundle.EditComprasRequiredMessage_fecha}" showOn="button"/>
                        <p:outputLabel value="#{bundle.CreateComprasLabel_proveedor}" for="proveedor" />
                        <p:selectOneMenu id="proveedor" value="#{comprasController.selected.proveedor}" required="true" requiredMessage="#{bundle.EditComprasRequiredMessage_proveedor}">
                            <f:selectItems value="#{proveedoresController.itemsAvailableSelectOne}"
                                           var="proveedorItem"
                                           itemValue="#{proveedorItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.CreateComprasLabel_id}" for="id" />
                        <p:inputText id="id" value="#{comprasController.selected.id}" title="#{bundle.CreateComprasTitle_id}" />
                            <p:outputLabel value="Producto" />
                            <p:outputLabel value="Cantidad" />
                    
                    </p:panelGrid>
                    

                    <ui:repeat value="#{productosController.items}" var="producto">
                         <h:panelGrid columns="2" style="width:100%" rendered="#{ventasController.selected != null}">
                            <h:outputText value="#{producto.nombre}" />
                            <p:inputNumber maxValue="#{producto.existencia}" value="#{producto.existencia}"/>
                         </h:panelGrid>
                    </ui:repeat>
                    <p:commandButton actionListener="#{comprasController.create}" value="#{bundle.Save}" update="display,:ComprasListForm:datalist,:growl" oncomplete="handleSubmit(args,'ComprasCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="ComprasCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

src/main/webapp/compras/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ComprasEditDlg" widgetVar="ComprasEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditComprasTitle}">
            <h:form id="ComprasEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{comprasController.selected != null}">
                        <p:outputLabel value="#{bundle.EditComprasLabel_productos}" for="productos" />
                        <p:selectOneMenu id="productos" value="#{comprasController.selected.productos}" required="true" requiredMessage="#{bundle.EditComprasRequiredMessage_productos}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{productosController.itemsAvailableSelectOne}"
                                           var="productosItem"
                                           itemValue="#{productosItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.EditComprasLabel_fecha}" for="fecha" />
                        <p:calendar id="fecha" pattern="MM/dd/yyyy" value="#{comprasController.selected.fecha}" title="#{bundle.EditComprasTitle_fecha}" required="true" requiredMessage="#{bundle.EditComprasRequiredMessage_fecha}" showOn="button"/>
                        <p:outputLabel value="#{bundle.EditComprasLabel_proveedor}" for="proveedor" />
                        <p:selectOneMenu id="proveedor" value="#{comprasController.selected.proveedor}" required="true" requiredMessage="#{bundle.EditComprasRequiredMessage_proveedor}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{proveedoresController.itemsAvailableSelectOne}"
                                           var="proveedorItem"
                                           itemValue="#{proveedorItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.EditComprasLabel_id}" for="id" />
                        <p:inputText id="id" value="#{comprasController.selected.id}" title="#{bundle.EditComprasTitle_id}" />
                            <p:outputLabel value="Producto" />
                            <p:outputLabel value="Cantidad" />
                    
                    </p:panelGrid>
                    

                    <ui:repeat value="#{productosController.items}" var="producto">
                         <h:panelGrid columns="2" style="width:100%" rendered="#{ventasController.selected != null}">
                            <h:outputText value="#{producto.nombre}" />
                            <p:inputNumber maxValue="#{producto.existencia}" value="#{producto.existencia}"/>
                         </h:panelGrid>
                    </ui:repeat>
                    <p:commandButton actionListener="#{comprasController.update}" value="#{bundle.Save}" update="display,:ComprasListForm:datalist,:growl" oncomplete="handleSubmit(args, 'ComprasEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="ComprasEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

src/main/webapp/compras/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListComprasTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="ComprasListForm">
                <p:panel header="#{bundle.ListComprasTitle}">
                    <p:dataTable id="datalist" value="#{comprasController.items}" var="item"
                                 selectionMode="single" selection="#{comprasController.selected}"
                                 paginator="true"
                                 rowKey="#{item.id}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column sortBy="#{item.productos.nombre}" filterBy="#{item.productos.nombre}"
                          filterMatchMode="contains">
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListComprasTitle_productos}"/>
                            </f:facet>
                            <h:outputText value="#{item.productos.nombre}"/>
                        </p:column>
                        <p:column sortBy="#{item.fecha}" filterBy="#{item.fecha}"
                          filterMatchMode="contains">
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListComprasTitle_fecha}"/>
                            </f:facet>
                            <h:outputText value="#{item.fecha}">
                                <f:convertDateTime pattern="MM/dd/yyyy" />
                            </h:outputText>
                        </p:column>
                        <p:column sortBy="#{item.proveedor.nombre}" filterBy="#{item.proveedor.nombre}"
                          filterMatchMode="contains">
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListComprasTitle_proveedor}"/>
                            </f:facet>
                            <h:outputText value="#{item.proveedor.nombre}"/>
                        </p:column>
                        <p:column sortBy="#{item.id}" filterBy="#{item.id}"
                          filterMatchMode="contains">
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListComprasTitle_id}"/>
                            </f:facet>
                            <h:outputText value="#{item.id}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{comprasController.prepareCreate}" update=":ComprasCreateForm" oncomplete="PF('ComprasCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":ComprasViewForm" oncomplete="PF('ComprasViewDialog').show()" disabled="#{empty comprasController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":ComprasEditForm" oncomplete="PF('ComprasEditDialog').show()" disabled="#{empty comprasController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle.Delete}" actionListener="#{comprasController.destroy}" update=":growl,datalist" disabled="#{empty comprasController.selected}"/>
                            <p:commandButton value="Exportar como Excel" ajax="false">
                                  <p:dataExporter type="xlsx" target="datalist" fileName="compras"/>
                           </p:commandButton>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

src/main/webapp/compras/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ComprasViewDlg" widgetVar="ComprasViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewComprasTitle}">
            <h:form id="ComprasViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{comprasController.selected != null}">
                        <h:outputText value="#{bundle.ViewComprasLabel_productos}"/>
                        <h:outputText value="#{comprasController.selected.productos}" title="#{bundle.ViewComprasTitle_productos}"/>
                        <h:outputText value="#{bundle.ViewComprasLabel_fecha}"/>
                        <h:outputText value="#{comprasController.selected.fecha}" title="#{bundle.ViewComprasTitle_fecha}">
                            <f:convertDateTime pattern="MM/dd/yyyy" />
                        </h:outputText>
                        <h:outputText value="#{bundle.ViewComprasLabel_proveedor}"/>
                        <h:outputText value="#{comprasController.selected.proveedor}" title="#{bundle.ViewComprasTitle_proveedor}"/>
                        <h:outputText value="#{bundle.ViewComprasLabel_id}"/>
                        <h:outputText value="#{comprasController.selected.id}" title="#{bundle.ViewComprasTitle_id}"/>
                            <p:outputLabel value="Producto" />
                            <p:outputLabel value="Cantidad" />
                    
                    </p:panelGrid>
                    

                    <ui:repeat value="#{productosController.items}" var="producto">
                         <h:panelGrid columns="2" style="width:100%" rendered="#{ventasController.selected != null}">
                            <h:outputText value="#{producto.nombre}" />
                            <p:inputNumber maxValue="#{producto.existencia}" value="#{producto.existencia}"/>
                         </h:panelGrid>
                    </ui:repeat>
                    <p:commandButton value="#{bundle.Close}" onclick="ComprasViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>